spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false
  liquibase:
    enabled: true
    drop-first: true
    default-schema: streaming
    liquibase-schema: streaming
